MODE: 1             # 1: train, 2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           : test, 3: eval
SEED: 10            # random seed
GPU: [0]            # list of gpu ids
MODEL: 1            # 1: ImagineGAN, 2: INN
DATATYPE: 1         # 1: objects, 2:scenes

TRAIN_FLIST: ./dataset/Places2/train.flist
VAL_FLIST: ./dataset/Places2/test.flist
NOISE_TRAIN_FLIST: ./dataset/Places2/train_noise.flist
NOISE_TRAIN_AUX: 
NOISE_VAL_FLIST: ./dataset/Places2/test_noise.flist

LR: 0.0002                    # learning rate
G_LR: 0.0001
D_LR: 0.0002
BETA1: 0.0                    # adam optimizer beta1
BETA2: 0.9                    # adam optimizer beta2
BATCH_SIZE: 4                 # input batch size for training
INPUT_SIZE: 256               # input image size for training 0 for original size
MAX_ITERS: 700000             # maximum number of iterations to train the model
CENTER: 0
CATMASK: True                 # True or False
MEAN: [0.5,0.5,0.5]     # mean value
STD: [0.5,0.5,0.5]      # standard deviation
COARSE_ITE: 0
MASK_TYPE: freeform     # freeform or pollute or graffiti or test or occlusion
N_UPDATE_E: 1
N_UPDATE_I: 1

G1_ADV_LOSS_WEIGHT: 0.1
G1_CONTENT_LOSS_WEIGHT: 1
G1_COLOR_LOSS_WEIGHT: 10
G1_MUTUAL_LOSS_WEIGHT: 5

G2_ADV_LOSS_WEIGHT: 0.1
G2_L1_LOSS_WEIGHT: 2
G2_STYLE_LOSS_WEIGHT: 250
G2_COLOR_LOSS_WEIGHT: 10
G2_MRF_LOSS_WEIGHT: 0.05
G2_MUTUAL_LOSS_WEIGHT: 5

KLD_LOSS_WEIGHT: 0.001

INTERVAL: 10000
SAMPLE_SIZE: 4                # number of images to sample

SAVE_INTERAL: 100000
